### basic settings

# site properties and page defaults
title: Keping Bi
description: Associate Professor at Information of Computing Technology (ICT), Chinese Academy of Sciences (CAS)
logo: images/logo.jpg
# header: images/background.jpg
# footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  google-scholar: kJQYiFIAAAAJ
  github: KepingBi
  twitter: BiKeping
  linkedin: keping-bi-b62a3437

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  # dblp-link: https://dblp.uni-trier.de/pid/169/1808.ris #Qingyao
  dblp-link: https://dblp.uni-trier.de/pid/56/10886.ris
  output: ../_data/citations.yaml
  depth: 100

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_alumni
  - scope:
      type: "alumni"
    values:
      layout: alumni
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true
  alumni:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
