### basic settings

# site properties and page defaults
title: Qingyao Ai
description: Assistant Professor at Department of Computer Science and Technology, Tsinghua University
logo: images/logo.png
header: images/background.jpg
footer: images/background.jpg
baseurl: "/group/~aiqy"

# site social media and other links
links:
  google-scholar: UKqaI5IAAAAJ
  github: QingyaoAi
  twitter: QingyaoAi
  linkedin: qingyao-ai-4ab8306a

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  dblp-link: https://dblp.uni-trier.de/pid/169/1808.ris
  output: ../_data/citations.yaml
  depth: 100

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_alumni
  - scope:
      type: "alumni"
    values:
      layout: alumni
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true
  alumni:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
